### PR TITLE
Handling zero-variance columns with random forest

### LINKED ISSUE #170: oblique random forests and zero-variance columns
filtro was silently reporting zero importances for all predictors when any single column had a single unique value (due to a failure of `aorsf::orsf()`)

``` r
library(filtro)

zv_reg_data <- mtcars
zv_reg_data$potato <- rep(1.0, 32)
zv_reg_data$kartoffel <- factor(rep("a", 32))

set.seed(42)
score_imp_rf_oblique |>
  fit(mpg ~ ., data = zv_reg_data) |> 
  purrr::pluck("results")
#> # A tibble: 12 × 4
#>    name           score outcome predictor
#>    <chr>          <dbl> <chr>   <chr>    
#>  1 imp_rf_oblique     0 mpg     cyl      
#>  2 imp_rf_oblique     0 mpg     disp     
#>  3 imp_rf_oblique     0 mpg     hp       
#>  4 imp_rf_oblique     0 mpg     drat     
#>  5 imp_rf_oblique     0 mpg     wt       
#>  6 imp_rf_oblique     0 mpg     qsec     
#>  7 imp_rf_oblique     0 mpg     vs       
#>  8 imp_rf_oblique     0 mpg     am       
#>  9 imp_rf_oblique     0 mpg     gear     
#> 10 imp_rf_oblique     0 mpg     carb     
#> 11 imp_rf_oblique     0 mpg     potato   
#> 12 imp_rf_oblique     0 mpg     kartoffel

# because: 

set.seed(42)
fit_aorsf <- aorsf::orsf(
  formula = mpg ~ .,
  data = zv_reg_data,
  importance = "permute"
)
#> Error: column potato is constant.
```

<sup>Created on 2025-08-20 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

We should remove these beforehand and give only those ZV columns an importance of zero.

### PR DESCRIPTION
**Pull request by topepo**
Closes #170 

This adds a utility function to find the offending predictors and some code in the random forest fitting function to avoid it. 

I also refactored some of the RF unit tests to make their arguments and results a little more consistent.

### CODE REVIEW

File: R/score-forest_imp.R [hunk 1]
```diff
@@ -233,14 +244,13 @@ S7::method(fit, class_score_imp_rf) <- function(
   }
 
   if (inherits(imp, "try-error")) {
-    imp <- NA_real_
+    cli::cli_warn("Random forest importance calucations errored with: {imp}")
```
Comment (topepo) [inline R/score-forest_imp.R:247]: We weren't logging model failures so I did it here.

File: R/score-forest_imp.R [hunk 2]
```diff
@@ -233,14 +244,13 @@ S7::method(fit, class_score_imp_rf) <- function(
...
+    imp <- rep(NA_real_, length(predictors))
```
Comment (topepo) [inline R/score-forest_imp.R:248]: I think that, instead of zeros, we should return NA values (so that they might become fallback values). Zero, to me, means that there is no utility in the predictors. If the model doesn't run, we don't really know that.

File: R/score-forest_imp.R [hunk 3]
```diff
@@ -233,14 +244,13 @@ S7::method(fit, class_score_imp_rf) <- function(
...
   }
 
-  score <- imp[predictors]
-  score[is.na(score)] <- 0
-  score <- stats::setNames(score, nm = predictors) # TODO Confirm this is the right approach
+  imp <- c(imp, zv_vec)
```
Comment (topepo) [inline R/score-forest_imp.R:251]: All of the random forest models return a named list so I simplified this and avoid more zeros from failed predictor calculations.

File: tests/testthat/test-score-forest_imp.R [hunk 4]
```diff
@@ -209,28 +209,32 @@ test_that("computations - regression task via ranger vary trees, mtry, min_n", {
 
 test_that("computations - classification task via partykit", {
   skip_if_not_installed("modeldata")
-  cells_subset <- helper_cells() |> dplyr::slice(1:20)
+  cells_subset <- helper_cells() |> dplyr::slice(1:200)
```
Comment (topepo) [inline tests/testthat/test-score-forest_imp.R:212]: As noted below, I could not get the scores to be the same, even with using the same seed. To deal with this I numbed up the data and trees so that the importances between calls should be highly correlated with one another. Then below I used `rank()` to make sure that they order the same.

File: tests/testthat/test-score-forest_imp.R [hunk 5]
```diff
@@ -387,24 +402,24 @@ test_that("computations - regression task via aorsf - adding missing values and
...
-    imp_aorsf,
+    imp_aorsf_merge$score,
+    imp_aorsf_merge$raw,
     tolerance = 0.1
   )
 
   # ----------------------------------------------------------------------------
   # case weights
-  two_weights <- c(rep(1, 10), rep(0, nrow(ames_subset) - 10))
+  two_weights <- seq(0, 1, length.out = nrow(ames_subset))
```
Comment (topepo) [inline tests/testthat/test-score-forest_imp.R:422]: I was getting a model failure with only a few non-zero weights. The results were consistent (i.e., zeros). I changed it to dense weights for each row.

File: DESCRIPTION [hunk 6]
```diff
@@ -29,7 +29,8 @@ Imports:
     S7,
     stats,
     tibble,
-    tidyr
+    tidyr,
+    vctrs
```
[the remark this answers is not in the document]
Comment (EmilHvitfeldt) [reply DESCRIPTION:33]: and we already have vctrs because of tidyr and dplyr anyways

File: R/utilities.R [hunk 7]
```diff
@@ -886,3 +886,21 @@ convert_weights <- function(weights, num_rows, call = rlang::caller_env()) {
   # extra class(es) and attributes
   as.numeric(weights)
 }
+
+find_zero_variance_cols <- function(data) {
```
Comment (EmilHvitfeldt) [inline R/utilities.R:890]:
```suggestion
# The first column is assumed to be the outcome
find_zero_variance_cols <- function(data) {
```

File: tests/testthat/test-score-forest_imp.R [hunk 8]
```diff
@@ -441,3 +497,26 @@ test_that("computations - required packages", {
...
+  expect_equal(
+    filtro:::find_zero_variance_cols(mtcars),
+    character(0)
+  )
+  expect_snapshot(
+    filtro:::find_zero_variance_cols(data.frame(y = rep(1, 5), x = 1:5)),
+    error = TRUE
+  )
+  expect_snapshot(
+    filtro:::find_zero_variance_cols(data.frame(y = rep(1, 5), x = rep(1, 5))),
```
Comment (EmilHvitfeldt) [inline tests/testthat/test-score-forest_imp.R:516]:
```suggestion
    filtro:::find_zero_variance_cols(data.frame(y = 1:5, x = rep(1, 5))),
```

This test currently doesn't hit the second guard

**Review by EmilHvitfeldt — APPROVED** [review]
